cask_args appdir: '/Applications'

brew 'coreutils'
brew 'openssl'
brew 'node'
brew 'ruby-build'
brew 'rbenv'
brew 'imagemagick'
brew 'grc'
brew 'yarn'
brew 'v8'
brew 'zsh-syntax-highlighting'
brew 'mysql'

cask 'sublime-text'
cask 'spotify'
cask 'dropbox'
cask 'steam'
cask 'iterm2'
cask 'transmission'
cask 'vlc'
cask 'framer'
cask 'firefox'
cask 'google-chrome'
cask 'sequel-pro'
cask 'goofy'
cask 'java'
cask 'appcleaner'
cask 'basecamp'
