#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit
else
  echo "  + Homebrew found."
fi



# Install grc and coreutils
brew install grc coreutils

# Install Hombebrew casks
brew tap phinze/cask
brew install brew-cask

brew cask install appcleaner grabbox rdio utorrent onepassword skype teamviewer dropbox vlc steam
brew cask install sourcetree brackets iterm2 sequel-pro firefox google-chrome google-drive